const htmlPdf = require('html-pdf-node');

const generateInvoicePDF = async (invoiceData) => {
  const {
    invoiceNumber,
    issuedDate,
    clientName,
    clientEmail,
    freelancerName,
    freelancerEmail,
    items,
    subtotal,
    platformFee,
    total,
    currency = 'USD',
  } = invoiceData;

  const itemsHTML = items.map((item) => `
    <tr>
      <td style="padding: 10px; border-bottom: 1px solid #eee;">${item.description}</td>
      <td style="padding: 10px; border-bottom: 1px solid #eee; text-align: right;">$${item.amount.toFixed(2)}</td>
    </tr>
  `).join('');

  const html = `
  <!DOCTYPE html>
  <html>
  <head>
    <style>
      body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
      .header { display: flex; justify-content: space-between; margin-bottom: 40px; }
      .logo { font-size: 28px; font-weight: bold; color: #6366f1; }
      .invoice-details { text-align: right; color: #666; }
      .parties { display: flex; justify-content: space-between; margin-bottom: 30px; }
      .party h4 { margin: 0 0 8px; color: #6366f1; }
      table { width: 100%; border-collapse: collapse; }
      th { background: #6366f1; color: white; padding: 12px; text-align: left; }
      .totals { margin-top: 20px; text-align: right; }
      .total-final { font-size: 20px; font-weight: bold; color: #6366f1; }
      .footer { margin-top: 60px; text-align: center; color: #999; font-size: 12px; }
    </style>
  </head>
  <body>
    <div class="header">
      <div class="logo">PayLance</div>
      <div class="invoice-details">
        <div><strong>Invoice #${invoiceNumber}</strong></div>
        <div>Issued: ${issuedDate}</div>
      </div>
    </div>

    <div class="parties">
      <div class="party">
        <h4>Bill From</h4>
        <div>${freelancerName}</div>
        <div>${freelancerEmail}</div>
      </div>
      <div class="party">
        <h4>Bill To</h4>
        <div>${clientName}</div>
        <div>${clientEmail}</div>
      </div>
    </div>

    <table>
      <thead>
        <tr>
          <th>Description</th>
          <th style="text-align:right">Amount (${currency})</th>
        </tr>
      </thead>
      <tbody>${itemsHTML}</tbody>
    </table>

    <div class="totals">
      <p>Subtotal: $${subtotal.toFixed(2)}</p>
      <p>Platform Fee (10%): -$${platformFee.toFixed(2)}</p>
      <p class="total-final">You Receive: $${total.toFixed(2)}</p>
    </div>

    <div class="footer">
      Generated by PayLance &bull; Freelance Marketplace Platform
    </div>
  </body>
  </html>`;

  const file = { content: html };
  const options = { format: 'A4', printBackground: true, margin: { top: '20px', bottom: '20px', left: '20px', right: '20px' } };
  const pdfBuffer = await htmlPdf.generatePdf(file, options);

  return pdfBuffer;
};

module.exports = { generateInvoicePDF };
